version: '3.8'

services:
  builder:
    container_name: builder
    image: builder
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=builder
        - LOCATION=builder
    ports:
      - 3000:3000
